# Generated by Django 5.2 on 2025-05-03 10:26

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True)),
                ('address_raw', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('archived', models.BooleanField(default=False)),
                ('work_formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ON_SITE', 'Офис'), ('REMOTE', 'Удалённо'), ('HYBRID', 'Гибрид'), ('FIELD_WORK', 'Разъездная работа')], max_length=20), blank=True, default=list, size=None)),
                ('work_time', models.CharField(blank=True, choices=[('HOURS_2', '2\u202fч'), ('HOURS_4', '4\u202fч'), ('HOURS_6', '6\u202fч'), ('HOURS_8', '8\u202fч')], max_length=20, null=True)),
                ('work_schedule', models.CharField(blank=True, choices=[('SEVEN_ON_ZERO_OFF', '7/0'), ('FIVE_ON_TWO_OFF', '5/2'), ('TWO_ON_TWO_OFF', '2/2')], max_length=30, null=True)),
                ('required_experience', models.CharField(blank=True, choices=[('noExperience', 'Нет опыта'), ('between1and3', '1‑3\u202fгода'), ('between3and6', '3‑6\u202fлет'), ('moreThan6', 'более 6-ти лет')], max_length=20, null=True)),
                ('areas', models.ManyToManyField(related_name='vacancies', to='vacancies.area')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_VIEWED', 'Не просмотрено'), ('REJECTED', 'Отклонено'), ('APPROVED', 'Одобрено'), ('INTERVIEW_CONFIRMED', 'Собес. назначено'), ('CLOSED', 'Закрыто')], default='NOT_VIEWED', max_length=30)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.PositiveIntegerField()),
                ('letter', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
