# Generated by Django 5.2 on 2025-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_remove_candidateresponse_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresponse',
            name='desired_role',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
